/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SwimObjects.Match;
import SwimObjects.ScoreBoard;
import SwimObjects.SwimmingCompetition;
import SwimObjects.TouchPad;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.table.DefaultTableModel;
import people.Judge;
import people.Spectator;
import people.SupportingStaff;
import people.Swimmer;

/**
 *
 * @author Hasini
 */
public class StartMatch extends javax.swing.JFrame {
    SwimmingCompetition  sc = SwimmingCompetition.getSwimmingCompetition();
    Match m;
    TouchPad tp ;
    ScoreBoard board = ScoreBoard.getScoreBoard();
    ArrayList<Swimmer> swimmer;
    private ArrayList<Swimmer> selectedSwimmer = new ArrayList<>() ;
    private ArrayList<Judge> judges;
    private ArrayList<JSlider> selectedSwimLanes = new ArrayList<>();
    private ArrayList<JLabel> selectedtouchpad = new ArrayList<>();
    
    
    
    
    private boolean gender;
    private boolean selected;
    private int ageRange ;
    private int style ;
    private int select_Judge;
   
    
    
    
    
    

    /**
     * Creates new form SwimmingCom2
     */
    public StartMatch() {
        
        initComponents();
        //setLocationRelativeTo(null);
        //setExtendedState(StartMatch.MAXIMIZED_BOTH);
        judges = sc.getAllJudges();
        for(int i = 0 ;i<judges.size();i++){
          add_Judge.addItem(judges.get(i).getName());
        }
        
        
    }
    private boolean isFinished = false;
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        age_range = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        match_style = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        mButton = new javax.swing.JRadioButton();
        fButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        getSwimmer = new javax.swing.JButton();
        MainMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        Select = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        swimmer1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        swimmer2 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        swimmer3 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        swimmer4 = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        swimmer5 = new javax.swing.JSlider();
        swimmerName1 = new javax.swing.JLabel();
        swimmerName2 = new javax.swing.JLabel();
        swimmerName3 = new javax.swing.JLabel();
        swimmerName4 = new javax.swing.JLabel();
        swimmerName5 = new javax.swing.JLabel();
        laneName2 = new javax.swing.JLabel();
        laneName3 = new javax.swing.JLabel();
        laneName4 = new javax.swing.JLabel();
        laneName5 = new javax.swing.JLabel();
        laneName1 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        touchPad3 = new javax.swing.JLabel();
        touchPad2 = new javax.swing.JLabel();
        touchPad4 = new javax.swing.JLabel();
        touchPad5 = new javax.swing.JLabel();
        touchPad1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        getWinners = new javax.swing.JButton();
        spectators_icon2 = new javax.swing.JLabel();
        spectators_icon1 = new javax.swing.JLabel();
        spectators_icon3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add_Judge = new javax.swing.JComboBox();
        getNewMatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Age Range :");

        age_range.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        age_range.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...............", "Under 12", "Under 15", "Under 17", "Under 19", "Open Catagory" }));
        age_range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_rangeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Style :");

        match_style.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        match_style.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".......................", "Free Style", "Back Stroke", "Butterfly Stroke", "Breast Stroke" }));
        match_style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                match_styleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Gender :");

        buttonGroup1.add(mButton);
        mButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        mButton.setText("Male");
        mButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mButtonMouseClicked(evt);
            }
        });
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fButton);
        fButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        fButton.setText("Female");
        fButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButtonMouseClicked(evt);
            }
        });
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });

        tbl.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index Number", "Name"
            }
        ));
        tbl.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getSwimmer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        getSwimmer.setText("Get Swimmers");
        getSwimmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getSwimmerMouseClicked(evt);
            }
        });

        MainMenu.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        MainMenu.setText("Main Menu");
        MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuMouseClicked(evt);
            }
        });
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "1"},
                {null, null, "2"},
                {null, null, "3"},
                {null, null, "4"},
                {null, null, "5"}
            },
            new String [] {
                "Index Number", "Name", "Swim Lane"
            }
        ));
        tbl1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(tbl1);
        if (tbl1.getColumnModel().getColumnCount() > 0) {
            tbl1.getColumnModel().getColumn(0).setMinWidth(50);
            tbl1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        Select.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Select.setText(">>>>>>>");
        Select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        swimmer1.setBackground(new java.awt.Color(0, 51, 255));
        swimmer1.setValue(0);
        jPanel2.add(swimmer1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        swimmer2.setBackground(new java.awt.Color(0, 51, 255));
        swimmer2.setValue(0);
        jPanel3.add(swimmer2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        swimmer3.setBackground(new java.awt.Color(0, 51, 255));
        swimmer3.setValue(0);
        jPanel4.add(swimmer3, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.BorderLayout());

        swimmer4.setBackground(new java.awt.Color(0, 51, 255));
        swimmer4.setValue(0);
        jPanel5.add(swimmer4, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        swimmer5.setBackground(new java.awt.Color(0, 51, 255));
        swimmer5.setValue(0);
        jPanel6.add(swimmer5, java.awt.BorderLayout.CENTER);

        swimmerName1.setBackground(new java.awt.Color(255, 255, 153));
        swimmerName1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        swimmerName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        swimmerName2.setBackground(new java.awt.Color(255, 255, 153));
        swimmerName2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        swimmerName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        swimmerName3.setBackground(new java.awt.Color(255, 255, 153));
        swimmerName3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        swimmerName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        swimmerName4.setBackground(new java.awt.Color(255, 255, 153));
        swimmerName4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        swimmerName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        swimmerName5.setBackground(new java.awt.Color(255, 255, 153));
        swimmerName5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        swimmerName5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        laneName2.setBackground(new java.awt.Color(255, 255, 153));
        laneName2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        laneName2.setText(" Lane 02");
        laneName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        laneName3.setBackground(new java.awt.Color(255, 255, 153));
        laneName3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        laneName3.setText(" Lane 03");
        laneName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        laneName4.setBackground(new java.awt.Color(255, 255, 153));
        laneName4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        laneName4.setText(" Lane 04");
        laneName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        laneName5.setBackground(new java.awt.Color(255, 255, 153));
        laneName5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        laneName5.setText(" Lane 05");
        laneName5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        laneName1.setBackground(new java.awt.Color(255, 255, 153));
        laneName1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        laneName1.setText(" Lane 01");
        laneName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        start.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        start.setText("START");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        touchPad3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        touchPad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        touchPad2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        touchPad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        touchPad4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        touchPad4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        touchPad5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        touchPad5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        touchPad1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        touchPad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index Number", "Name", "Total time(ms)", "Place"
            }
        ));
        tbl2.setGridColor(new java.awt.Color(204, 0, 0));
        jScrollPane3.setViewportView(tbl2);
        if (tbl2.getColumnModel().getColumnCount() > 0) {
            tbl2.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl2.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("SCORE BOARD");

        getWinners.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        getWinners.setText("Get Winners");
        getWinners.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getWinnersMouseClicked(evt);
            }
        });
        getWinners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getWinnersActionPerformed(evt);
            }
        });

        spectators_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/spectator_watch.jpg"))); // NOI18N

        spectators_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/spectator_watch.jpg"))); // NOI18N

        spectators_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/spectator_watch.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("Judge : ");

        add_Judge.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        add_Judge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "............" }));
        add_Judge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_JudgeActionPerformed(evt);
            }
        });

        getNewMatch.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        getNewMatch.setText("New Match");
        getNewMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getNewMatchMouseClicked(evt);
            }
        });
        getNewMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNewMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laneName4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimmerName4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(touchPad4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laneName5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimmerName5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(touchPad5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laneName1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimmerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(touchPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laneName3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimmerName3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(touchPad3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(match_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(age_range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(add_Judge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(mButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(fButton))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(getSwimmer)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Select, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spectators_icon1)
                                .addGap(1, 1, 1)
                                .addComponent(spectators_icon2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spectators_icon3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getWinners)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getNewMatch))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laneName2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swimmerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(touchPad2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4, jPanel5, jPanel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(match_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(mButton)
                                            .addComponent(fButton)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(age_range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(add_Judge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MainMenu)
                                    .addComponent(getSwimmer))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spectators_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spectators_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(spectators_icon3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(start)
                            .addComponent(getWinners)
                            .addComponent(getNewMatch))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laneName1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(swimmerName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(touchPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laneName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swimmerName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(touchPad2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laneName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swimmerName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(touchPad3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laneName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swimmerName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(touchPad4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laneName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swimmerName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(touchPad5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {laneName1, laneName2, laneName3, laneName4, laneName5, swimmerName1, swimmerName2, swimmerName3, swimmerName4, swimmerName5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4, jPanel5, jPanel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void age_rangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_rangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_rangeActionPerformed

    private void mButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButtonMouseClicked
        gender = false;
        selected = true;
    }//GEN-LAST:event_mButtonMouseClicked

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mButtonActionPerformed

    private void fButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButtonMouseClicked
        gender = true;
        selected = true;
    }//GEN-LAST:event_fButtonMouseClicked
    private boolean isGetSwimmerClicked = false;
     
    private void getSwimmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getSwimmerMouseClicked
        isGetSwimmerClicked = true;
        DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();       
        dtm.setRowCount(0);
        ageRange = age_range.getSelectedIndex();
        style = match_style.getSelectedIndex();
        select_Judge = add_Judge.getSelectedIndex();
         if(ageRange==0){
            JOptionPane.showMessageDialog(jPanel1, "Please select an age range");
        }if(style==0){
            JOptionPane.showMessageDialog(jPanel1, "Please select a style");
        }if(selected == false){
            JOptionPane.showMessageDialog(jPanel1, "Please select a gender");
        }if(select_Judge==0){
            JOptionPane.showMessageDialog(jPanel1, "Please select a judge");
        }else{                
                m = new Match(gender,style,ageRange);
                m.setJudge(judges.get(select_Judge-1));             
                swimmer = sc.getSwimmers(m);
                if(swimmer.size()!=0){
                    for(Swimmer s : swimmer){
                    dtm.addRow(new Object[]{s.getIndexNumber(),s.getName()});
                    } 
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No swimmers");
                }
                    
                             
        }
        
    }//GEN-LAST:event_getSwimmerMouseClicked
    
   
    private void MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseClicked
        if(isNewMatchClicked){
            setVisible(false);
            MainMenu m = new MainMenu();
            m.setVisible(true);
        }else{
            int i =JOptionPane.showConfirmDialog(rootPane, "Still you havent finished the match. Are you sure you want to go to main menu?", null, 0, 0);
            switch (i){
                case 0:
                    setVisible(false);
                    MainMenu m = new MainMenu();
                    m.setVisible(true);
                    break;
                case 1:
                    break;
                default:
                    JOptionPane.showConfirmDialog(rootPane, "Still you havent finished the match. Are you sure you want to go to main menu?", null, 0, 0);
            }
           
        }
       
    }//GEN-LAST:event_MainMenuMouseClicked
    private int selection = 0;
    private boolean isSelectClicked = false;
    private void SelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectMouseClicked
        isSelectClicked=true;
        if(isGetSwimmerClicked){
            DefaultTableModel dtm1=(DefaultTableModel)tbl1.getModel();
            DefaultTableModel dtm=(DefaultTableModel) tbl.getModel();
            DefaultTableModel dtm2=(DefaultTableModel) tbl2.getModel();
            JLabel[] swimmerName = {swimmerName1,swimmerName2,swimmerName3,swimmerName4,swimmerName5};
            JSlider[] swimLane = {swimmer1,swimmer2,swimmer3,swimmer4,swimmer5};
            JLabel[] touchPad = {touchPad1,touchPad2,touchPad3,touchPad4,touchPad5};
            int number=tbl.getSelectedRow();      
            if(number!=-1 && selection<5){
                dtm1.setValueAt(tbl.getValueAt(number, 0), selection,0);
                dtm1.setValueAt(tbl.getValueAt(number, 1), selection,1);
                swimmerName[selection].setText("     "+(String)tbl.getValueAt(number, 1));
                dtm.removeRow(number);
                for(Swimmer s: swimmer){
                    if((Integer)dtm1.getValueAt(selection, 0)==s.getIndexNumber()){
                        selectedSwimmer.add(s);
                        s.setSwimLane(selection+1);
                        selectedSwimLanes.add(swimLane[selection]);
                        selectedtouchpad.add(touchPad[selection]);
                        dtm2.addRow(new Object[]{s.getIndexNumber(),s.getName()});
                    }
                }            
                selection++;            
            }
            
       }else{
            JOptionPane.showMessageDialog(rootPane,"First Click the getSwimmer button");
        }
  
        
        
      
    }//GEN-LAST:event_SelectMouseClicked

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        
    }//GEN-LAST:event_startActionPerformed
    private boolean isStartClicked = false;
    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        if(isSelectClicked){
                
                final Random ran = new Random();
                final DefaultTableModel dtm2=(DefaultTableModel) tbl2.getModel();
                //final ArrayList<Integer> indexArray = new ArrayList<>() ;
                final ArrayList<Long> time = new ArrayList<>();
                ArrayList<Thread> threadArray = new ArrayList<>() ;
                
               
                for(final JSlider j : selectedSwimLanes){
                    Runnable r = new Runnable() {
                        final int index = selectedSwimLanes.indexOf(j);
                        public void run() {
                            long startTime = System.currentTimeMillis(); 
                            while(true){
                                try {
                                    //.setStyle(m.getMatchstyle());                                   
                                    j.setValue(j.getValue()+selectedSwimmer.get(index).swim(m.getMatchstyle()));
                                    //j.setValue(j.getValue()+Location.getLocation(selectedSwimmer.get(index)));
                                    if(j.getValue()==100){
                                        long endTime = System.currentTimeMillis();
                                        long t = endTime-startTime;
                                        tp = new TouchPad(selectedSwimmer.get(index), t, true);
                                        sc.addTouchPad(tp);
                                        selectedSwimmer.get(index).touchTouchPad(tp);                           
                                        selectedSwimmer.get(index).setTime(t);
                                        selectedtouchpad.get(index).setText("   FINISH");  
                                        dtm2.setValueAt(selectedSwimmer.get(index).getTime(), index, 2);
                                        break;
                                    }
                                    Thread.sleep(200);
                                } catch (InterruptedException ex) {

                                }
                            }

                            }
                        };
                        Thread t = new Thread(r);
                        threadArray.add(t);
                    }
                for(Thread t : threadArray){
                    t.start();
                }
                
               
              
                isStartClicked = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Fist select five swimmers");
        }        
       
    }//GEN-LAST:event_startMouseClicked
    private boolean isWinnerClicked = false;
    private void getWinnersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getWinnersMouseClicked
        if(isStartClicked){
            final DefaultTableModel dtm2=(DefaultTableModel) tbl2.getModel();
            board.setWinners();
            board.setMatch(m);
                for(Swimmer s :board.getSwimmer() ){
                    for(int x = 0;x<dtm2.getRowCount();x++){
                        if(s.getIndexNumber()==(int)dtm2.getValueAt(x, 0)){
                            dtm2.setValueAt(s.getRank(), x, 3);
                        }
                    }
                }
                String Address = "/GUI/spectator_watch.jpg";
                for(Spectator s :sc.getAllSpectator()){
                      Address = board.notifySpectator(s);
                }
                for(Judge j :sc.getAllJudges()){
                      j.setResult(board.getSwimmer());
                }
                for(SupportingStaff ss:sc.getAllStaff()){
                      ss.setResult(board.getSwimmer());
                }
                spectators_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Address)));
                spectators_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource(Address)));
                spectators_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Address)));
                isWinnerClicked=true;
                sc.addMatch(m);
                board.clearScoreBorad();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "First click the start button");
        }
        
        
        
    }//GEN-LAST:event_getWinnersMouseClicked

    private void getWinnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getWinnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getWinnersActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuActionPerformed

    private void match_styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_match_styleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_match_styleActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButtonActionPerformed

    private void add_JudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_JudgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_JudgeActionPerformed
    //private boolean isSaveClicked = false;    
    private boolean isNewMatchClicked = false;
    private void getNewMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getNewMatchMouseClicked
            if(isWinnerClicked){
                isNewMatchClicked=true;
                StartMatch sm = new StartMatch();
                sm.setVisible(true);
                setVisible(false);
            }
            
       else{
            JOptionPane.showMessageDialog(rootPane, "First press the get winners");
        }
       
    }//GEN-LAST:event_getNewMatchMouseClicked

    private void getNewMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNewMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNewMatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu;
    private javax.swing.JButton Select;
    private javax.swing.JComboBox add_Judge;
    private javax.swing.JComboBox age_range;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fButton;
    private javax.swing.JButton getNewMatch;
    private javax.swing.JButton getSwimmer;
    private javax.swing.JButton getWinners;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel laneName1;
    private javax.swing.JLabel laneName2;
    private javax.swing.JLabel laneName3;
    private javax.swing.JLabel laneName4;
    private javax.swing.JLabel laneName5;
    private javax.swing.JRadioButton mButton;
    private javax.swing.JComboBox match_style;
    private javax.swing.JLabel spectators_icon1;
    private javax.swing.JLabel spectators_icon2;
    private javax.swing.JLabel spectators_icon3;
    private javax.swing.JButton start;
    private javax.swing.JSlider swimmer1;
    private javax.swing.JSlider swimmer2;
    private javax.swing.JSlider swimmer3;
    private javax.swing.JSlider swimmer4;
    private javax.swing.JSlider swimmer5;
    private javax.swing.JLabel swimmerName1;
    private javax.swing.JLabel swimmerName2;
    private javax.swing.JLabel swimmerName3;
    private javax.swing.JLabel swimmerName4;
    private javax.swing.JLabel swimmerName5;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JLabel touchPad1;
    private javax.swing.JLabel touchPad2;
    private javax.swing.JLabel touchPad3;
    private javax.swing.JLabel touchPad4;
    private javax.swing.JLabel touchPad5;
    // End of variables declaration//GEN-END:variables
}
